ln -s ~/archdots/bash/.bashrc ~/.bashrc
ln -s ~/archdots/.face ~/.face
ln -s ~/archdots/wallpapers ~/Pictures/wallpapers
ln -s ~/archdots/.config/bspwm ~/.config/bspwm
ln -s ~/archdots/.config/polybar ~/.config/polybar
ln -s ~/archdots/.config/termite ~/.config/termite
ln -s ~/archdots/.config/rofi ~/.config/rofi
ln -s ~/archdots/.config/nitrogen ~/.config/nitrogen
ln -s ~/archdots/.config/xsettingsd ~/.config/xsettingsd
ln -s ~/archdots/.config/Kvantum ~/.config/Kvantum
ln -s ~/archdots/.config/qt5ct ~/.config/qt5ct
ln -s ~/archdots/.config/mimeapps.list ~/.config/mimeapps.list
ln -s ~/archdots/.local/kservices5 ~/.local/share/kservices5